["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
ERC20 = [
    "src/contracts/mock/ERC20.cairo",
]
flashmining = [
    "src/contracts/mock/Flashmining.cairo",
]
flashminingborrower = [
    "src/contracts/mock/FlashminingBorrower.cairo",
]